apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-task-cluster
  region: ap-south-1

nodeGroups:
   - name: ng-micro
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: eks_task_key
   - name: ng-small
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: eks_task_key
   - name: spot-instance-ng
     minSize: 2
     maxSize: 5
     instancesDistribution:
       maxPrice: 0.017
       instanceTypes: ["t3.small", "t3.medium"] 
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: eks_task_key
